# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
annotations:
  TOOLCHAIN_ID: null
  GIT_URL: null
  GIT_BRANCH: null
  GIT_COMMIT: null
  USER_NAME: null
  APPLICATION_VERSION: null
image:
  repository: <helm-repo>
  tag: <helm-tag>
  pullSecret: regsecret
  pullPolicy: IfNotPresent
workload:
  command: workload.sh